# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/producer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/producer.proto',
  package='airbloc.producer',
  syntax='proto3',
  serialized_pb=_b('\n\x14proto/producer.proto\x12\x10\x61irbloc.producer\".\n\nIdentifier\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nidentifier\x18\x02 \x01(\t\"h\n\x07RawData\x12\x15\n\rcategoryOfApp\x18\x01 \x01(\t\x12\x35\n\x0fownerIdentifier\x18\x02 \x01(\x0b\x32\x1c.airbloc.producer.Identifier\x12\x0f\n\x07payload\x18\x03 \x01(\t\"<\n\x0e\x41\x64\x64\x44\x61taSummary\x12\x15\n\rinsertedCount\x18\x01 \x01(\r\x12\x13\n\x0b\x65lapsedTime\x18\x02 \x01(\x04\x32V\n\x08Producer\x12J\n\x07\x41\x64\x64\x44\x61ta\x12\x19.airbloc.producer.RawData\x1a .airbloc.producer.AddDataSummary\"\x00(\x01\x62\x06proto3')
)




_IDENTIFIER = _descriptor.Descriptor(
  name='Identifier',
  full_name='airbloc.producer.Identifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='airbloc.producer.Identifier.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='airbloc.producer.Identifier.identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=88,
)


_RAWDATA = _descriptor.Descriptor(
  name='RawData',
  full_name='airbloc.producer.RawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='categoryOfApp', full_name='airbloc.producer.RawData.categoryOfApp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ownerIdentifier', full_name='airbloc.producer.RawData.ownerIdentifier', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='airbloc.producer.RawData.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=194,
)


_ADDDATASUMMARY = _descriptor.Descriptor(
  name='AddDataSummary',
  full_name='airbloc.producer.AddDataSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='insertedCount', full_name='airbloc.producer.AddDataSummary.insertedCount', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elapsedTime', full_name='airbloc.producer.AddDataSummary.elapsedTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=256,
)

_RAWDATA.fields_by_name['ownerIdentifier'].message_type = _IDENTIFIER
DESCRIPTOR.message_types_by_name['Identifier'] = _IDENTIFIER
DESCRIPTOR.message_types_by_name['RawData'] = _RAWDATA
DESCRIPTOR.message_types_by_name['AddDataSummary'] = _ADDDATASUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identifier = _reflection.GeneratedProtocolMessageType('Identifier', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFIER,
  __module__ = 'proto.producer_pb2'
  # @@protoc_insertion_point(class_scope:airbloc.producer.Identifier)
  ))
_sym_db.RegisterMessage(Identifier)

RawData = _reflection.GeneratedProtocolMessageType('RawData', (_message.Message,), dict(
  DESCRIPTOR = _RAWDATA,
  __module__ = 'proto.producer_pb2'
  # @@protoc_insertion_point(class_scope:airbloc.producer.RawData)
  ))
_sym_db.RegisterMessage(RawData)

AddDataSummary = _reflection.GeneratedProtocolMessageType('AddDataSummary', (_message.Message,), dict(
  DESCRIPTOR = _ADDDATASUMMARY,
  __module__ = 'proto.producer_pb2'
  # @@protoc_insertion_point(class_scope:airbloc.producer.AddDataSummary)
  ))
_sym_db.RegisterMessage(AddDataSummary)



_PRODUCER = _descriptor.ServiceDescriptor(
  name='Producer',
  full_name='airbloc.producer.Producer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=258,
  serialized_end=344,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddData',
    full_name='airbloc.producer.Producer.AddData',
    index=0,
    containing_service=None,
    input_type=_RAWDATA,
    output_type=_ADDDATASUMMARY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCER)

DESCRIPTOR.services_by_name['Producer'] = _PRODUCER

# @@protoc_insertion_point(module_scope)
